# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04  # Consider using 22.04 for stability unless 24.04 is needed
  tools:
    python: "3.12"  # Consider using 3.11 or 3.12 unless 3.13 is strictly needed

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   # CORRECTED PATH: Point to conf.py inside the 'source' directory
   configuration: docs/source/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   # Install documentation build dependencies
   - requirements: docs/requirements.txt
   # ADDED: Install the project itself so autodoc can import it
   - method: pip
     path: .