# This is the environment file for the `spaceborne` conda environment to be used on macOS machines

name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - joblib
  - numba
  - camb>=1.5.0
  - healpy
  - pyqt
  - ipympl
  - cfitsio

  # for CCL:
  - fftw
  - gsl
  - swig
  - cmake
  - make
  - libgfortran-ng
  - fast-pt
  - pyccl>=3.2.0

  # required by OneCovariance (optional, comment out if you 
  # don't want to use it)
  - gfortran
  - pybind11

  - pip:
    - pymaster
    - cython
    - getdist
    - pyfiglet # for the fancy ascii art, not really needed

# In case of issues with CCL, you can try running
# brew install gfortran cmake build-essential autoconf bison
