# This is the environment file for the `spaceborne` conda environment to be used on Linux machines

name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - joblib
  - numba
  - camb>=1.5.0
  - gcc
  - healpy
  - pyqt
  - ipympl
  - cfitsio
  
  # for CCL:
  - fftw
  - gsl
  - swig
  - cmake
  - make
  - libgcc-ng
  - libgfortran-ng
  - libstdcxx-ng
  - fast-pt
  - pyccl>=3.1.0

  # required by OneCovariance (optional, comment out if you 
  # don't want to use it)
  - gfortran
  - pybind11

  - pip:
    - pymaster
    - cython
    - getdist

# In case of issues with CCL, you can try running
# $ sudo apt-get install gfortran cmake build-essential autoconf bison
