# This is the environment file for the `spaceborne` conda environment to be used on macOS machines

name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - matplotlib
  - numpy
  - scipy
  - pandas
  - tqdm
  - pip
  - pyyaml
  - astropy
  - joblib
  - numba
  - camb
  - healpy
  - pyqt
  - ipympl
  - cfitsio

  # for CCL:
  - fftw
  - gsl
  - swig
  - cmake
  - make
  - libgfortran-ng
  - fast-pt
  - pyccl
  # - cfitsio  # not necessary?
  - pip:
    - pymaster
    - cython
    - getdist

# In case of issues with CCL, you can try
# brew install gfortran cmake build-essential autoconf bison
