# This is the environment file for the `spaceborne` conda environment to be used on Linux machines

name: spaceborne
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11
  - matplotlib
  - numpy
  - scipy
  - tqdm
  - pip
  - pyyaml
  - joblib
  - healpy>=1.18.0
  - camb

  # PyCCL depenedencies
  - swig
  - cmake

  # pymaster dependencies
  - cfitsio
  - fftw
  - gsl

  - pip:
    # pathos is needed to parallelize the computations involving non-pickleable objects.
    # It can be ignored, in which some functions will run serially
    # - pathos  
    # - pymaster
    - pylevin
    - pyfiglet # for the fancy ascii art, not strictly necessary
