def build_oc_ini(cfg):
    
       config_data = {
            'covariance terms': {
                'gauss': True,
                'split_gauss': False,
                'nongauss': False,
                'ssc': False
            },
            'observables': {
                'cosmic_shear': True,
                'est_shear': 'xi_pm',
                'ggl': True,
                'est_ggl': 'gamma_t',
                'clustering': True,
                'est_clust': 'w',
                'cstellar_mf': False,
                'cross_terms': True,
                'unbiased_clustering': False,
            },
            'output settings': {
                'directory': f'./output_2PCF_{case_id}/',
                'file': 'covariance_list.dat, covariance_matrix.mat',
                'style': 'list, matrix',
                'list_style_spatial_first': True,
                'corrmatrix_plot': 'correlation_coefficient.pdf',
                'save_configs': 'save_configs.ini',
                'save_Cells': True,
                'save_trispectra': False,
                'save_alms': True,
                'use_tex': False,
            },
            'covELLspace settings': {
                'ell_min': 2,
                'ell_max': 5000,
                'ell_bins': 20,
                'ell_type': 'log',
                'delta_z': 0.08,
                'tri_delta_z': 0.5,
                'integration_steps': 500,
                'nz_interpolation_polynom_order': 1,
                'mult_shear_bias': '0, 0, 0, 0, 0, 0, 0, 0, 0, 0' ,
                'limber': True,
                'pixelised_cell': False,
                'pixel_Nside': 2048,
                'n_spec': 0,
            },
            'covTHETAspace settings': {
                'theta_min': 6,
                'theta_max': 600,
                'theta_bins': 40,
                'theta_type': 'log',
                'xi_pp': True,
                'xi_mm': True,
                'theta_accuracy': 1e-4,
                'integration_intervals': 400,
            },
            'survey specs': {
                'survey_area_clust_in_deg2': 14851.06604979094,
                'survey_area_ggl_in_deg2': 14851.06604979094,
                'survey_area_lensing_in_deg2': 14851.06604979094,
                'ellipticity_dispersion': '0.26, ' * zbins,
                'n_eff_clust': str(list(n_eff_values)),
                'n_eff_lensing': str(list(n_eff_values)),
            },
            'redshift': {
                'value_loc_in_clustbin': 'center',
                'value_loc_in_lensbin': 'center',
                'z_directory': f'{output_path}/OneCovariance',
                'zclust_file':  f'nzTab-forOneCov-{recipe}.ascii',
                'zlens_file':  f'nzTab-forOneCov-{recipe}.ascii',
            },
            
        }